# Config file for automatic testing at travis-ci.org
language: python
python:
  - "3.5"
env:
  - TOX_ENV=py27-django18
  - TOX_ENV=py35-django18
  - TOX_ENV=py27-django19
  - TOX_ENV=py35-django19
  - TOX_ENV=py27-django110
  - TOX_ENV=py35-django110
install:
  - pip install tox
script:
  - tox -e $TOX_ENV
  - make coverage
  - make lint
